# SPDX-FileCopyrightText: Copyright (c) 2022-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.


ARG L4T_VERSION


# Jetson Thor is SBSA based

FROM nvcr.io/nvidia/cuda:13.0.0-tensorrt-runtime-ubuntu24.04

RUN apt-key adv --fetch-keys https://repo.download.nvidia.com/jetson/jetson-ota-public.asc
RUN echo "deb https://repo.download.nvidia.com/jetson/common r38.2 main" >> /etc/apt/sources.list

# needed to add apt-repo
RUN DEBIAN_FRONTEND=noninteractive apt-get update ;  apt-get install -y --no-install-recommends software-properties-common


RUN mkdir -p /lib/firmware ; mkdir -p /root/tmp ; mkdir -p /tmp99 ; ls -ltr /root ;  \
        apt-add-repository ppa:mosquitto-dev/mosquitto-ppa ; apt-get update && \
        DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        rsyslog git \
        tzdata \
        wget \
        tar \
        libgstrtspserver-1.0-0 \
        gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-tools \
        libgstrtspserver-1.0-0 libgstrtspserver-1.0-dev \
        libjansson4 \
        libglib2.0-dev \
        libjson-glib-1.0-0 \
        librabbitmq4 \
        gstreamer1.0-rtsp \
        libgstreamer1.0-0 \
        gstreamer1.0-tools \
        libyaml-cpp-dev \
        libjsoncpp-dev \
        libjpeg-dev \
        openssl \
        libssl3 \
        build-essential \
        libssl-dev \
        libcurl4-openssl-dev \
        libcjson-dev \
        libnvvpi4 \
        vpi4-dev \
        apparmor-utils \
        mosquitto \
        libhiredis-dev \
        librdkafka1 \ 
        ca-certificates && \
        rm -rf /var/lib/apt/lists/* && \
        rm -rf /root/tmp && \       
        apt autoremove

RUN --mount=type=bind,src=jetson_dockerfiles,target=/tmp/docker \
        tar --version ; mkdir -p /root/tmp ; mkdir -p /tmp99 ; ls -ltr /root ; tar -xvf /tmp/docker/deepstream_sdk_v8.0.0_jetson.tbz2 -C / ; /opt/nvidia/deepstream/deepstream/install.sh && \
        cp /tmp/docker/rsyslog /etc/init.d/  && \
        chmod +x /etc/init.d/rsyslog && \
        ln -s /usr/lib/aarch64-linux-gnu/nvidia /usr/lib/aarch64-linux-gnu/tegra && \
        ln -s /usr/src/tensorrt/bin/trtexec /usr/bin/trtexec && \
        cp /tmp/docker/entrypoint.sh /opt/nvidia/deepstream/deepstream/ && \
        chmod +x /opt/nvidia/deepstream/deepstream/entrypoint.sh && \
        cp  /tmp/docker/user_additional_install_runtime.sh /opt/nvidia/deepstream/deepstream/ && \
        cp  /tmp/docker/LicenseAgreementContainer.pdf /opt/nvidia/deepstream/deepstream/ && \
        mv  /opt/nvidia/deepstream/deepstream/user_additional_install_runtime.sh /opt/nvidia/deepstream/deepstream/user_additional_install.sh && \
        rm -rf /var/lib/apt/lists/* && \
        rm -rf /root/tmp && \
        apt autoremove 

# WAR for CUDA compatability so DeepStream will run without errors with JP 7.0 / JP 7.1 - 580.xx drivers
RUN apt purge -y cuda-compat-13-0


# IP requirement for removal
RUN rm -f /usr/lib/aarch64-linux-gnu/libavresample* /usr/lib/aarch64-linux-gnu/libavutil* \
        /usr/lib/aarch64-linux-gnu/libavcodec* /usr/lib/aarch64-linux-gnu/libavformat* \
        /usr/lib/aarch64-linux-gnu/libavfilter*
RUN rm -f /usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstaudioparsers.so \
        /usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstfaad.so
RUN rm -f /usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstvoaacenc.so \
        /usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstx264.so /usr/lib/aarch64-linux-gnu/libx264.so*  \
        /usr/lib/aarch64-linux-gnu/libmpeg2.so* /usr/lib/aarch64-linux-gnu/libmpeg2convert.so* /usr/lib/aarch64-linux-gnu/libmpeg2encpp-2.1.so* 
RUN rm -f  /usr/lib/aarch64-linux-gnu/libmpg123.so* /usr/lib/aarch64-linux-gnu/libvpx.so* /usr/lib/aarch64-linux-gnu/libx265.so*  \
        /usr/lib/aarch64-linux-gnu/libde265.so* /usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstx265.so*  \
        /usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstde265.so* /usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstvpx.so \
        /usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstopenh264.so /usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvcodec.so

# new IP additions

RUN rm -f /usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstuvch264.so /usr/lib/aarch64-linux-gnu/libopenh264.so.2.2.0 /usr/lib/aarch64-linux-gnu/libopenh264.so* \
        /usr/lib/aarch64-linux-gnu/libvo-aacenc.so.0 /usr/lib/aarch64-linux-gnu/libvo-aacenc.so.0.0.4 /usr/lib/aarch64-linux-gnu/libmp3lame.so.0.0.0 \
        /usr/lib/aarch64-linux-gnu/libmp3lame.so.0 /usr/lib/aarch64-linux-gnu/libfaad* /usr/lib/aarch64-linux-gnu/libFLAC.so* \
        /usr/lib/aarch64-linux-gnu/libmjpegutils-2.1.so.0* /usr/lib/aarch64-linux-gnu/libxvidcore.so* /usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstmpegpsmux.so \
        /usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstflac.so \
        /usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstmpeg2enc.so /usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstmpeg2dec.so

RUN rm -f /usr/lib/*-linux-gnu/libdca.so* /usr/lib/*-linux-gnu/libdvdnav.so* /usr/lib/*-linux-gnu/libdvdread.so* \
          /usr/lib/*-linux-gnu/libmpeg2.so.0* /usr/lib/*-linux-gnu/libmpeg2encpp-2.1.so* /usr/lib/*-linux-gnu/libmpg123.so*


CMD ["/bin/bash"]
WORKDIR /opt/nvidia/deepstream/deepstream


RUN ln -s /usr/local/cuda-13.0/targets/sbsa-linux/lib/libcufft.so.12.0.0.15 /usr/local/cuda-13.0/targets/sbsa-linux/lib/libcufft.so
RUN ln -s /usr/local/cuda-13.0/targets/sbsa-linux/lib/libcublas.so.13.0.0.19 /usr/local/cuda-13.0/targets/sbsa-linux/lib/libcublas.so

# Workaround for deepstream-app --version-all
RUN ln -s /usr/lib/aarch64-linux-gnu/libcudnn.so.9.12.0 /usr/lib/aarch64-linux-gnu/libcudnn.so
RUN ln -s /usr/local/cuda-13.0/targets/sbsa-linux/lib/libcudart.so.13.0.48 /usr/local/cuda-13.0/targets/sbsa-linux/lib/libcudart.so


ENTRYPOINT ["/opt/nvidia/deepstream/deepstream/entrypoint.sh"]

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-13.0/lib64

ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=all

RUN ldconfig

